### PR TITLE
Create 0000-01-02-johncschuster.md

### PR DESCRIPTION
**Pull request by johncschuster**
add header to file

### CODE REVIEW

**Review by johncschuster — COMMENTED** [review]
add Shake Shaq

**Comment by johncschuster** [comment]
Can you merge this PR for me?

**Review by johncschuster — COMMENTED** [review]
please review

**Comment by johncschuster** [comment]
Hello @hollenberry / @hectorsector! Nice to meet you!

It looks like Github Learning Bot is stuck at merging my PR, and I'm unable to do it. Would you mind merging the PR for me?

Thanks! ❤️

**Comment by hollenberry** [comment]
Hey @johncschuster ! Unfortunately @hectorsector and I don't have any permissions here, but I think it looks like you're set up and ready to merge!

If you're having any issues troubleshooting, mind dropping us a line in https://github.community/t5/GitHub-Learning-Lab/bd-p/learn ? 

This forum is monitored daily and the best way to get at a reliable and quick response ✨ . Good luck, keep it up!

**Pull request merged**
